apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-internal-tls
spec:
  secretName: alertmanager-tls-server
  duration: 2160h
  renewBefore: 1440h
  issuerRef:
    name: monitoring-internal-ca
    kind: Issuer
  dnsNames:
    - alerts.crcd.pitt.edu
    - alerts
    - alerts.crcd-monitoring
    - alerts.crcd-monitoring.svc
    - alerts.crcd-monitoring.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-public-tls
spec:
  secretName: alertmanager-public-tls
  issuerRef:
    name: sectigo-issuer
    kind: ClusterIssuer
  dnsNames:
    - alerts.crcd.pitt.edu