fullnameOverride: alertmanager

service:
  type: LoadBalancer

persistence:
  storageClass: pitt-vcf-vks-storage-policy-latebinding

podSecurityContext:
  fsGroup: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault